---
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Course Overview

Network *science* is a paradigm (i.e. a model of how the world works) that takes as its domain of interest the interdependence among units. This paradigm examines patterns or regularities in relationships (i.e. *structure*) among interacting units and focuses on a) how such patterns influence the behavior of these units and b) how such patterns are generated. *Network criminology* is a relatively new, loosely organized (but rapidly growing) body of research that applies concepts and methods from network science to problems in criminology and criminal justice. This course provides an introduction to a broad range of concepts from what might be considered “classic” or “foundational” works in network science. The overarching goal of the course is to provide you the tools for thinking about problems in criminology and criminal justice through a network lens (i.e. viewing systems as made up of heterogeneous actors connected through different types of relations). 

<br>
<br>

## Topics ([syllabus](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_files/CRJ_523_Networks_SYLLABUS.pdf))
____

<br>

### Introduction

<br>

#### Network Basics
  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_Week_1_SLIDES.pdf)

<br>

#### Introduction to Network Criminology
  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_Week_2_SLIDES.pdf)  
  
  + [Theory Table](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_files/CRJ_523_Networks_THEORY_TABLE.pdf) 

  + [General Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_files/CRJ_523_Networks_DISCUSSION_QUESTIONS.pdf) 

<br>
<br>

### Section One: Thinking About Networks in Criminology 

*This section examines several topical areas that have drawn on science to test existing theories or better understand prevailing questions in the discipline.*

<br>

#### Peer Influence, Co-Offending, and Gangs
  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_Week_3_SLIDES.pdf) 

  + [Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_files/CRJ_523_Networks_DISCUSSION_W3.pdf)  


<br>


#### Neighborhood Ecology and Criminal Opportunity
  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_Week_4_SLIDES.pdf)   

  + [Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_files/CRJ_523_Networks_DISCUSSION_W4.pdf)  


<br>


### Section Two: Network Foundations

*This section examines several topics that can be described as foundational concepts in network science. The reading(s) in the “Network Concept(s)” section serves as an introduction to the concept and the “Criminological Application” section serves as the application of those ideas to topics in criminology and criminal justice.*

<br>

#### Homophily

  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_Week_5_SLIDES.pdf)   
  
  + [Discussant Presentation](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Week_5_PRESENTATION.pdf)

  + [Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Week_5_QUESTIONS.pdf)  

<br>

#### Embeddedness

  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_EMBEDDEDNESS_SLIDES.pdf)   

  + [Discussant Presentation](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_EMBEDDEDNESS_PRESENTATION.pdf)

  + [Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_EMMBEDDEDNESS_QUESTIONS.pdf)   

<br>

#### Social Capital and Resource Mobilization

  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_SOCIAL_CAPITAL_SLIDES.pdf)   

  + [Discussant Presentation](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_SOCIAL_CAPITAL_PRESENTATION.pdf)

  + [Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_SOCIAL_CAPITAL_QUESTIONS.pdf)   

<br>

#### Multiplexity

  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_MULTIPLEXITY_SLIDES.pdf)   

  + [Discussant Presentation](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_MULTIPLEXITY_PRESENTATION.pdf)

  + [Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_MULTIPLEXITY_QUESTIONS.pdf)  

<br>

#### Contagion & Diffusion

  + [Slides](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_lectures/CRJ_523_CONTAGION_SLIDES.pdf)  
  
   + [Discussant Presentation](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_CONTAGION_DIFFUSION_PRESENTATION.pdf)

  + [Discussion Questions](https://github.com/jacobtnyoung/NetworkCriminology/raw/main/_presentations/CRJ_523_Networks_CONTAGION_DIFFUSION_QUESTIONS.pdf)  
  

<br>

#### Status and Hierarchy Formation

  + [Slides]()  
  
  + [Discussant Presentation]()

  + [Discussion Questions]()  

<br>

#### Network Dynamics & Vulnerability

  + [Slides]()  
  
  + [Discussant Presentation]()

  + [Discussion Questions]()  

<br>

#### Network Interventions & Policy Considerations

  + [Slides]()  
  
  + [Discussant Presentation]()

  + [Discussion Questions]()  

<br>

<br>
<br>

###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***